// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the "Update Firebase Project" command.
export const firebaseConfig = {
  "projectId": "studio-4650436250-edd0b",
  "appId": "1:1026816586467:web:036f40227386e3ecef4bd6",
  "apiKey": "AIzaSyAuRc7hG3Zuv3ctK9r3Tvq-nZAsGdmR1Rc",
  "authDomain": "studio-4650436250-edd0b.firebaseapp.com",
  "storageBucket": "studio-4650436250-edd0b.appspot.com",
  "messagingSenderId": "1026816586467"
};
